version: '3'

volumes:
  cc_postgres_data: {}
  cc_postgres_data_backups: {}
  cc_redis_volume: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: cc_django
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - ./.envs_example/.django
      - ./.envs_example/.postgres
    ports:
      - "80:80"
    command: ["sh", "compose/django/start"]

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    container_name: cc_postgres
    restart: always
    volumes:
      - cc_postgres_data:/var/lib/postgresql/data
      - cc_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs_example/.postgres

  redis:
    image: redis:6
    container_name: cc_redis
    restart: always
    volumes:
      - cc_redis_volume:/data
    ports:
      - "6379:6379"

  celeryworker:
    <<: *django
    container_name: cc_celeryworker
    restart: always
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
