# Generated by Django 5.1.6 on 2025-03-10 09:46

import app.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptocurrencyTradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('slug', models.SlugField(default=app.utils.utils.get_random_uuid_hex, max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_tracking', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cryptocurrency Trading Pair',
                'verbose_name_plural': 'Cryptocurrency Trading Pairs',
                'db_table': 'crypto_trading_pair',
            },
        ),
        migrations.CreateModel(
            name='CryptocurrencyCostSnapshotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=28)),
                ('created_at', models.DateTimeField()),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshot_log', to='binance.cryptocurrencytradingpair')),
            ],
            options={
                'verbose_name': 'Cryptocurrency Cost Snapshot Log',
                'verbose_name_plural': 'Cryptocurrency Cost Snapshot Logs',
                'db_table': 'crypto_cost_snapshot_log',
            },
        ),
    ]
